version: '3.8'

services:
  zookeeper1:
    image: zookeeper:3.9.3
    hostname: zookeeper1
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,stat,ruok
    volumes:
      - zookeeper1_data:/data
      - zookeeper1_logs:/logs

  zookeeper2:
    image: zookeeper:3.9.3
    hostname: zookeeper2
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,stat,ruok
    volumes:
      - zookeeper2_data:/data
      - zookeeper2_logs:/logs

  zookeeper3:
    image: zookeeper:3.9.3
    hostname: zookeeper3
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,stat,ruok
    volumes:
      - zookeeper3_data:/data
      - zookeeper3_logs:/logs

  dining-philosophers:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: dining-philosophers
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    deploy:
      replicas: 3
    environment:
      - ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.routers.dining-philosophers.rule=Host(`dining-philosophers`) || PathPrefix(`/`)"
      - "traefik.http.services.dining-philosophers.loadbalancer.server.port=8080"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - dining-philosophers

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  traefik:
    image: traefik:3.3.6
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9080"
      - "--log.level=DEBUG"
    ports:
      - "9080:9080"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - dining-philosophers

volumes:
  zookeeper1_data:
  zookeeper1_logs:
  zookeeper2_data:
  zookeeper2_logs:
  zookeeper3_data:
  zookeeper3_logs:
  grafana_data: