{
 "title": "Dining philosophers",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Taux de pensée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(philosophers_state_duration_seconds_sum{state=\"think\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps moyen d'une pensée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(philosophers_state_duration_seconds_sum{state=\"think\"}[1m])/increase(philosophers_state_duration_seconds_count{state=\"think\"}[1m])",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Taux d'alimentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(philosophers_state_duration_seconds_sum{state=\"eat\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps moyen d'alimentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(philosophers_state_duration_seconds_sum{state=\"eat\"}[1m])/increase(philosophers_state_duration_seconds_count{state=\"eat\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'attente des fourchettes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(philosophers_state_duration_seconds_sum{state=\"take-fork\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps moyen pour prendre les fourchettes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(philosophers_state_duration_seconds_sum{state=\"take-fork\"}[1m])/increase(philosophers_state_duration_seconds_count{state=\"take-fork\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'attente pour reposer les fourchettes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(philosophers_state_duration_seconds_sum{state=\"release-fork\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps moyen pour reposer les fourchettes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(philosophers_state_duration_seconds_sum{state=\"release-fork\"}[1m])/increase(philosophers_state_duration_seconds_count{state=\"release-fork\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}